### ISSUE TITLE
Validar la conexión a internet

### ISSUE THREAD

**Issue by Carlos119** [Alexis1606/preparate#63]
Hacer método dentro de la aplicación para validar la conexión a internet y devolver un valor de 0 si no hay internet y 1 si si hay

**Comment by Carlos119** [comment]
Ya valida la conexión a internet

**Comment by Alexis1606** [comment]
Falta ver que te lleve a la pantalla correcta

**Comment by Alexis1606** [comment]
Se realiz[o la tarea
