### ISSUE TITLE
aviso de privacidad

### ISSUE THREAD

**Issue by Alexis1606** [Alexis1606/preparate#83]
Hay que hacer el aviso de privacidad y decidir la mejor forma de ponerlo:
- Todo el aviso dentro de la aplicación
- Un link para verlo en una página en internet.
- Un link para descargarlo
- ETC......

**Comment by Carlos119** [comment]
https://rua-ssb-prod.ec.lcred.net/doc_RUA/AVISOS_DE_PRIVACIDAD_rua_270811.pdf este es un ejemplo de aviso de privacidad 
y esta es una herramienta que funciona para que el IFAI cree un aviso de privacidad
http://www.e-consulta.com/nota/2013-09-14/sociedad/ifai-desarrolla-generador-de-avisos-de-privacidad-gratuito

**Comment by Carlos119** [comment]
https://drive.google.com/open?id=0B7jpuiiERGiSd1psVkJMd1I1Nms esta es la liga para revisar el aviso de privacidad
